import Link from "next/link"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AuthLayout({ children }) {
  return (
    <section className="bg-gray-100 h-screen">
      <div className="flex flex-col justify-center items-center gap-5 h-screen">
        <Link href={`/`}>Logo Store</Link>
        {children}
      </div>
    </section>
  )
}
